### PR TITLE
I put my name on the README

### PR DESCRIPTION
**Pull request by boustanip718**
I put my name on the README. :)

### Assignee Tasks

* [ ] added unit tests (or none needed)
* [ ] written relevant docs (or none needed)
* [ ] referenced any relevant issues (or none exist)

### Guidelines

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.

---

_Your PR Notes Here_

### CODE REVIEW

**Review by zernst3 — APPROVED** [review]
Approved!

**Review by agne-ur — APPROVED** [review]
Yay

**Review by holdMyGlasses — APPROVED** [review]
Works

**Comment by holdMyGlasses** [comment]
Cool

**Pull request merged**
